import { skillManager } from "./skillManager";
import { holyDimensionSkill } from "./spell/holyDimension";
import { ragingGravitySkill } from "./spell/ragingGravity";
import { redMagicSkill } from "./spell/redMagicSkill";
import { scannerSkill } from "./spell/scanner";
import { smokeBombSkill } from "./spell/smokeBomb";
import { assaultLance } from "./weapon/assaultLance";
import { drillRodSkill } from "./weapon/drillRod";
import { giantSwordSkill } from "./weapon/giantSword";
import { heroSwordSkill } from "./weapon/heroSword";
import { phantomSwordSkill } from "./weapon/phantomSword";
import { healBookSkill } from "./spell/healBook";
import { tntShotSkill } from "./spell/tntShot";
import { dashSwordSkill } from "./weapon/dashSword";
import { magicRevolverSkill } from "./weapon/magicRevolver";
import { explosiveAxeSkill } from "./weapon/explosiveAxe";
import { speedBootsSkill } from "./armor/speedBoots";
import { harubaguSpecialCatalogSKill } from "./spell/harubaguSpecialCatalog";
import { highSpeedSkill } from "./spell/highSpeed";
import { deathNoteSkill } from "./spell/deathNote";
import { magicTechGunSwordSkill } from "./weapon/magicTechGunSword";
import { slowHelmetSkill } from "./armor/slowHelmet";
import { superSlowHelmetSkill } from "./armor/superSlowHelmet";
import { regenerationChestPlateSkill } from "./armor/regenerationChestPlate";
import { superRegenerationChestPlateSkill } from "./armor/superRegenerationChestPlate";
import { pushFeatherSkill } from "./spell/pushFeather";
import { leapFeatherSkill } from "./spell/leapFeather";
import { blueBirdOfHappinessSkill } from "./spell/blueBirdOfHappiness";
import { jammingSwordSkill } from "./weapon/jammingSword";
import { thiefLeggingsSkill } from "./armor/thiefLeggings";
import { jumpLeggingsSkill } from "./armor/jumpLeggings";
import { superJumpLeggingsSkill } from "./armor/superJumpLeggings";
import { superSpeedBootsSkill } from "./armor/superSpeedBoots";
import { revengeChestPlateSkill } from "./armor/revengeChestPlate";
import { gyroKineticWandSkill } from "./spell/gyroKineticWand";
import { randomDiceSkill } from "./spell/randomDice";
import { changerSkill } from "./spell/changer";
import { curseSwordSkill } from "./weapon/curseSword";
import { returnSkill } from "./spell/return";
import { speedUpSkill } from "./spell/speedUp";
import { wallSkill } from "./armor/wall";
import { specialCookieSkill } from "./armor/specialCookie";
import { campfireHealSkill } from "./spell/camfireHeal";
import { vampireHelmetSkill } from "./armor/vampireHelmet";
import { miniMedicalKitSkill } from "./spell/miniMedicalKit";
import { medicalKitSkill } from "./spell/madicalKit";
import { cinderSwordSkill } from "./weapon/cinderSword";
import { dicerollSwordSkill } from "./weapon/dicerollSword";
import { handcuffsSkill } from "./spell/handcuffs";
import { dispelBladeSkill } from "./weapon/dispelBlade";
import { drainSwordSkill } from "./weapon/drainSword";
import { harubaguSpecialLevySKill } from "./spell/harubaguSpecialLevy";
import { totemChestPlateSkill } from "./armor/totemChestPlate";
import { greenMagicSKill } from "./spell/greenMagicSkill";
import { infernalAxeSkill } from "./weapon/infernalAxe";
import { deadbushSwordSkill } from "./weapon/deadbushSword";
import { breakArmorSKill } from "./spell/breakArmor";
import { crossSlashSkill } from "./weapon/crossSlash";
import { gateOfBabylonSkill } from "./spell/gateOfBabylon";
import { reflectArmorSkill } from "./armor/reflectArmor";
import { perfectReflectArmorSkill } from "./armor/perfectReflectArmor";
import { wheatSwordSkill } from "./weapon/wheatSword";
import { hellBladeSKill } from "./weapon/hellBlade";
import { healHelmetSkill } from "./armor/healHelmet";
import { thunderSword } from "./weapon/thunderSword";
import { brokenSwordSkill } from "./weapon/brokenSword";
import { robustHelmetSkill } from "./armor/robustHelmet";
import { fluffyBootsSkill } from "./armor/fluffyBoots";
import { breakerSkill, crusherSkill } from "./weapon/breaker";
import { assassinSkill } from "./spell/assassin";
import { swapperSkill } from "./spell/swapper";
import { returnAxeSkill } from "./weapon/returnAxe";
import { blowAwaySwordSkill } from "./weapon/blowAwaySword";
import { assassinBladeSkill } from "./weapon/assasinBlade";
import { trueAssassinBladeSkill } from "./weapon/trueAssasinBlade";
import { assaultArmorSkill } from "./armor/assaultArmor";
import { theEyeOfOrdinSkill } from "./armor/theEyeOfOdin";
import { weaknessSwordSkill } from "./weapon/weaknessSword";
import { sneakSpeedLeggingsSkill } from "./armor/sneakSpeedLeggings";
import { administratorSkill } from "./weapon/administrator";
import { windBurstSkill } from "./spell/windBurst";
import { affectSwordSkill } from "./weapon/affectSword";
import { hookshotSkill } from "./spell/hookshot";
import { flowerDashSkill } from "./spell/flowerDash";
import { confessionSkill } from "./spell/confession";
import { overwriteSkill } from "./spell/overwrite";
import { bloodySwordSkill } from "./weapon/bloodySword";
import { proteikosChestPlateSkill } from "./armor/proteikosChestPlate";
import { explosiveChestPlateSkill } from "./armor/explosiveChestPlate";
import { nightShroudSkill } from "./armor/nightShroud";
import { surviveBootsSkill } from "./armor/surviveBoots";
import { damageCutLeggingsSkill } from "./armor/damageCutLeggings";
import { disLoveSword } from "./weapon/disLoveSword";
import { absorptionSwordSkill } from "./weapon/absorptionSword";
import { counterLeggingsSkill } from "./armor/counterLeggings";
import { fightBackBootsSkill } from "./armor/fightBackBoots";
import { blowAwayArmorSkill } from "./armor/blowAwayArmor";
import { craftPickaxeSkill } from "./weapon/craftPickaxe";
import { dirtSwordSkill } from "./weapon/dirtSword";
import { stoneSwordSkill } from "./weapon/stoneSword";
import { phantomArmorSkill } from "./armor/phantomArmor";
import { endstoneSwordSkill } from "./weapon/endstoneSword";
import { wheatArmorSkill } from "./armor/wheatArmor";
import { scanHelmetSkill } from "./armor/scanHelmet";
import { breakTimeLeggings } from "./armor/breakTimeLeggings";
import { hyperKineticPositionReverser } from "./spell/hyperKineticPositionReverser";
import { ironDaggerSkill } from "./weapon/ironDagger";
import { subMachineGunSkill } from "./weapon/submachinegun";
import { igniteChestPlateSkill } from "./armor/igniteChestPlate";
import { bailoutChestPlate } from "./armor/bailoutChestPlate";
import { railgunSkill } from "./spell/railgun";
import { starChaserBootsSkill } from "./armor/starChaserBoots";
import { cookieArmorSkill } from "./armor/cookieArmor";
import { teleportSkill } from "./spell/teleport";
import { rainbowArmorSkill } from "./armor/rainbowArmor";
import { snowArmorSkill } from "./armor/snowArmor";
import { leafArmorSkill } from "./armor/leafArmor";
import { hyperionSkill } from "./weapon/hyperion";
import { vionlenceSwordSkill } from "./weapon/violenceSword";
import { valflameLeggingsSkill } from "./armor/valflameLeggings";
import { handgunSkill } from "./weapon/handgun";
import { furyHelmetSkill } from "./armor/furyHelmet";
import { jugglingSkill } from "./spell/juggling";
import { blackholeSkill } from "./spell/blackhole";
import { blazingSword } from "./weapon/blazingSword";
import { largePeopleBootsSkill } from "./armor/largePeopleBoots";
import { fewPeopleBootsSkill } from "./armor/fewPeopleBoots";
import { enhanceFernSkill } from "./weapon/enhanceFern";
import { iceBlockSkill } from "./spell/iceBlock";
import { dimensinalDriftSkill } from "./spell/dimensionalDrift";

skillManager.register(new redMagicSkill());
skillManager.register(new giantSwordSkill());
skillManager.register(new heroSwordSkill());
skillManager.register(new drillRodSkill());
skillManager.register(new scannerSkill());
skillManager.register(new holyDimensionSkill());
skillManager.register(new smokeBombSkill());
skillManager.register(new phantomSwordSkill());
skillManager.register(new assaultLance());
skillManager.register(new ragingGravitySkill());
skillManager.register(new healBookSkill());
skillManager.register(new tntShotSkill());
skillManager.register(new dashSwordSkill());
skillManager.register(new magicRevolverSkill());
skillManager.register(new explosiveAxeSkill());
skillManager.register(new harubaguSpecialCatalogSKill());
skillManager.register(new deathNoteSkill());
skillManager.register(new highSpeedSkill());
skillManager.register(new magicTechGunSwordSkill());
skillManager.register(new pushFeatherSkill());
skillManager.register(new leapFeatherSkill());
skillManager.register(new blueBirdOfHappinessSkill());
skillManager.register(new jammingSwordSkill());
skillManager.register(new thiefLeggingsSkill());
skillManager.register(new revengeChestPlateSkill());
skillManager.register(new gyroKineticWandSkill());
skillManager.register(new randomDiceSkill());
skillManager.register(new changerSkill());
skillManager.register(new curseSwordSkill());
skillManager.register(new returnSkill());
skillManager.register(new speedUpSkill());
skillManager.register(new wallSkill());
skillManager.register(new specialCookieSkill());
skillManager.register(new campfireHealSkill());
skillManager.register(new dicerollSwordSkill());
skillManager.register(new cinderSwordSkill());
skillManager.register(new miniMedicalKitSkill());
skillManager.register(new handcuffsSkill());
skillManager.register(new medicalKitSkill());
skillManager.register(new dispelBladeSkill());
skillManager.register(new drainSwordSkill());
skillManager.register(new harubaguSpecialLevySKill());
skillManager.register(new totemChestPlateSkill());
skillManager.register(new greenMagicSKill());
skillManager.register(new deadbushSwordSkill());
skillManager.register(new breakArmorSKill());
skillManager.register(new crossSlashSkill());
skillManager.register(new gateOfBabylonSkill());
skillManager.register(new reflectArmorSkill());
skillManager.register(new perfectReflectArmorSkill());
skillManager.register(new wheatSwordSkill());
skillManager.register(new hellBladeSKill());
skillManager.register(new healHelmetSkill());
skillManager.register(new thunderSword());
skillManager.register(new brokenSwordSkill());
skillManager.register(new breakerSkill());
skillManager.register(new crusherSkill());
skillManager.register(new assassinSkill());
skillManager.register(new swapperSkill());
skillManager.register(new returnAxeSkill());
skillManager.register(new blowAwaySwordSkill());
skillManager.register(new assassinBladeSkill());
skillManager.register(new trueAssassinBladeSkill());
skillManager.register(new assaultArmorSkill());
skillManager.register(new administratorSkill());
skillManager.register(new windBurstSkill());
skillManager.register(new affectSwordSkill());
skillManager.register(new hookshotSkill());
skillManager.register(new flowerDashSkill());
skillManager.register(new confessionSkill());
skillManager.register(new overwriteSkill());
skillManager.register(new bloodySwordSkill());
skillManager.register(new explosiveChestPlateSkill());
skillManager.register(new surviveBootsSkill());
skillManager.register(new damageCutLeggingsSkill());
skillManager.register(new disLoveSword());
skillManager.register(new absorptionSwordSkill());
skillManager.register(new counterLeggingsSkill());
skillManager.register(new blowAwayArmorSkill());
skillManager.register(new craftPickaxeSkill());
skillManager.register(new dirtSwordSkill());
skillManager.register(new stoneSwordSkill());
skillManager.register(new endstoneSwordSkill());
skillManager.register(new phantomArmorSkill());
skillManager.register(new vampireHelmetSkill());
skillManager.register(new hyperKineticPositionReverser());
skillManager.register(new subMachineGunSkill());
skillManager.register(new igniteChestPlateSkill());
skillManager.register(new bailoutChestPlate());
skillManager.register(new railgunSkill());
skillManager.register(new teleportSkill());
skillManager.register(new snowArmorSkill());
skillManager.register(new leafArmorSkill());
skillManager.register(new hyperionSkill());
skillManager.register(new vionlenceSwordSkill());
skillManager.register(new handgunSkill());
skillManager.register(new furyHelmetSkill());
skillManager.register(new jugglingSkill());
skillManager.register(new blackholeSkill());
skillManager.register(new enhanceFernSkill());
skillManager.register(new dimensinalDriftSkill());

skillManager.tickSkillRegister(new speedBootsSkill());
skillManager.tickSkillRegister(new superSpeedBootsSkill());
skillManager.tickSkillRegister(new slowHelmetSkill());
skillManager.tickSkillRegister(new superSlowHelmetSkill());
skillManager.tickSkillRegister(new regenerationChestPlateSkill());
skillManager.tickSkillRegister(new superRegenerationChestPlateSkill());
skillManager.tickSkillRegister(new jumpLeggingsSkill());
skillManager.tickSkillRegister(new superJumpLeggingsSkill());
skillManager.tickSkillRegister(new revengeChestPlateSkill());
skillManager.tickSkillRegister(new robustHelmetSkill());
skillManager.tickSkillRegister(new fluffyBootsSkill());
skillManager.tickSkillRegister(new assaultArmorSkill());
skillManager.tickSkillRegister(new theEyeOfOrdinSkill());
skillManager.tickSkillRegister(new sneakSpeedLeggingsSkill());
skillManager.tickSkillRegister(new proteikosChestPlateSkill());
skillManager.tickSkillRegister(new nightShroudSkill());
skillManager.tickSkillRegister(new fightBackBootsSkill());
skillManager.tickSkillRegister(new wheatArmorSkill());
skillManager.tickSkillRegister(new scanHelmetSkill());
skillManager.tickSkillRegister(new breakTimeLeggings());
skillManager.tickSkillRegister(new ironDaggerSkill());
skillManager.tickSkillRegister(new starChaserBootsSkill());
skillManager.tickSkillRegister(new cookieArmorSkill());
skillManager.tickSkillRegister(new rainbowArmorSkill());
skillManager.tickSkillRegister(new hyperionSkill());
skillManager.tickSkillRegister(new valflameLeggingsSkill());
skillManager.tickSkillRegister(new blazingSword());
skillManager.tickSkillRegister(new largePeopleBootsSkill());
skillManager.tickSkillRegister(new fewPeopleBootsSkill());
skillManager.tickSkillRegister(new iceBlockSkill());

const axeSkill = new infernalAxeSkill();

const axeNames = [
    "§1ぼろぼろの斧",
    "§5斧",
    "§6血の斧",
    "§d血まみれの斧",
    "§b業火の斧"
];

for (const name of axeNames) {
    const s = Object.create(axeSkill);
    s.id = name;
    skillManager.register(s);
}