import { skillManager } from "./skillManager";
import { holyDimensionSkill } from "./spell/holyDimension";
import { ragingGravitySkill } from "./spell/ragingGravity";
import { redMagicSkill } from "./spell/redMagicSkill";
import { scannerSkill } from "./spell/scanner";
import { smokeBombSkill } from "./spell/smokeBomb";
import { assaultLance } from "./weapon/assaultLance";
import { drillRodSkill } from "./weapon/drillRod";
import { giantSwordSkill } from "./weapon/giantSword";
import { heroSwordSkill } from "./weapon/heroSword";
import { phantomSwordSkill } from "./weapon/phantomSword";
import { healBookSkill } from "./spell/healBook";
import { tntShotSkill } from "./spell/tntShot";
import { dashSwordSkill } from "./weapon/dashSword";
import { magicRevolverSkill } from "./weapon/magicRevolver";
import { cosmicMeteorSkill } from "./weapon/cosmicMeteorSkill";
import { explosiveAxeSkill } from "./weapon/explosiveAxe";
import { speedBootsSkill } from "./armor/speedBoots";
import { harubaguSpecialCatalogSKill } from "./spell/harubaguSpecialCatalog";
import { highSpeedSkill } from "./spell/highSpeed";
import { deathNoteSkill } from "./spell/deathNote";
import { magicTechGunSwordSkill } from "./weapon/magicTechGunSword";
import { slowHelmetSkill } from "./armor/slowHelmet";
import { superSlowHelmetSkill } from "./armor/superSlowHelmet";
import { regenerationChestPlateSkill } from "./armor/regenerationChestPlate";
import { superRegenerationChestPlateSkill } from "./armor/superRegenerationChestPlate";
import { pushFeatherSkill } from "./spell/pushFeather";
import { leapFeatherSkill } from "./spell/leapFeather";
import { blueBirdOfHappinessSkill } from "./spell/blueBirdOfHappiness";
import { jammingSwordSkill } from "./weapon/jammingSword";
import { thiefLeggingsSkill } from "./armor/thiefLeggings";
import { jumpLeggingsSkill } from "./armor/jumpLeggings";
import { superJumpLeggingsSkill } from "./armor/superJumpLeggings";
import { superSpeedBootsSkill } from "./armor/superSpeedBoots";
import { revengeChestPlateSkill } from "./armor/revengeChestPlate";
import { gyroKineticWandSkill } from "./spell/gyroKineticWand";
import { randomDiceSkill } from "./spell/randomDice";
import { changerSkill } from "./spell/changer";
import { curseSwordSkill } from "./weapon/curseSword";
import { returnSkill } from "./spell/return";
import { speedUpSkill } from "./spell/speedUp";
import { wallSkill } from "./armor/wall";
import { specialCookieSkill } from "./armor/specialCookie";
import { campfireHealSkill } from "./spell/camfireHeal";
import { vampireHelmetSkill } from "./armor/vampireHelmet";
import { miniMedicalKitSkill } from "./spell/miniMedicalKit";
import { medicalKitSkill } from "./spell/madicalKit";
import { cinderSwordSkill } from "./weapon/cinderSword";
import { dicerollSwordSkill } from "./weapon/dicerollSword";
import { handcuffsSkill } from "./spell/handcuffs";
import { dispelBladeSkill } from "./weapon/dispelBlade";
import { drainSwordSkill } from "./weapon/drainSword";
import { harubaguSpecialLevySKill } from "./spell/harubaguSpecialLevy";
import { totemChestPlateSkill } from "./armor/totemChestPlate";
import { greenMagicSKill } from "./spell/greenMagicSkill";
import { infernalAxeSkill } from "./weapon/infernalAxe";
import { deadbushSwordSkill } from "./weapon/deadbushSword";
import { breakArmorSKill } from "./spell/breakArmor";
import { crossSlashSkill } from "./weapon/crossSlash";
import { gateOfBabylonSkill } from "./spell/gateOfBabylon";
import { reflectArmorSkill } from "./armor/reflectArmor";
import { perfectReflectArmorSkill } from "./armor/perfectReflectArmor";
import { wheatSwordSkill } from "./weapon/wheatSword";
import { hellBladeSKill } from "./weapon/hellBlade";

skillManager.register(new redMagicSkill());
skillManager.register(new giantSwordSkill());
skillManager.register(new heroSwordSkill());
skillManager.register(new drillRodSkill());
skillManager.register(new scannerSkill());
skillManager.register(new holyDimensionSkill());
skillManager.register(new smokeBombSkill());
skillManager.register(new phantomSwordSkill());
skillManager.register(new assaultLance());
skillManager.register(new ragingGravitySkill());
skillManager.register(new healBookSkill());
skillManager.register(new tntShotSkill());
skillManager.register(new dashSwordSkill());
skillManager.register(new magicRevolverSkill());
skillManager.register(new cosmicMeteorSkill());
skillManager.register(new explosiveAxeSkill());
skillManager.register(new harubaguSpecialCatalogSKill());
skillManager.register(new deathNoteSkill());
skillManager.register(new highSpeedSkill());
skillManager.register(new magicTechGunSwordSkill());
skillManager.register(new pushFeatherSkill());
skillManager.register(new leapFeatherSkill());
skillManager.register(new blueBirdOfHappinessSkill());
skillManager.register(new jammingSwordSkill());
skillManager.register(new thiefLeggingsSkill());
skillManager.register(new revengeChestPlateSkill());
skillManager.register(new gyroKineticWandSkill());
skillManager.register(new randomDiceSkill());
skillManager.register(new changerSkill());
skillManager.register(new curseSwordSkill());
skillManager.register(new returnSkill());
skillManager.register(new speedUpSkill());
skillManager.register(new wallSkill());
skillManager.register(new specialCookieSkill());
skillManager.register(new campfireHealSkill());
skillManager.register(new dicerollSwordSkill());
skillManager.register(new cinderSwordSkill());
skillManager.register(new miniMedicalKitSkill());
skillManager.register(new handcuffsSkill());
skillManager.register(new medicalKitSkill());
skillManager.register(new dispelBladeSkill());
skillManager.register(new drainSwordSkill());
skillManager.register(new harubaguSpecialLevySKill());
skillManager.register(new totemChestPlateSkill());
skillManager.register(new greenMagicSKill());
skillManager.register(new deadbushSwordSkill());
skillManager.register(new breakArmorSKill());
skillManager.register(new crossSlashSkill());
skillManager.register(new gateOfBabylonSkill());
skillManager.register(new reflectArmorSkill());
skillManager.register(new perfectReflectArmorSkill());
skillManager.register(new wheatSwordSkill());
skillManager.register(new hellBladeSKill());

skillManager.tickSkillRegister(new speedBootsSkill());
skillManager.tickSkillRegister(new superSpeedBootsSkill());
skillManager.tickSkillRegister(new slowHelmetSkill());
skillManager.tickSkillRegister(new superSlowHelmetSkill());
skillManager.tickSkillRegister(new regenerationChestPlateSkill());
skillManager.tickSkillRegister(new superRegenerationChestPlateSkill());
skillManager.tickSkillRegister(new jumpLeggingsSkill());
skillManager.tickSkillRegister(new superJumpLeggingsSkill());
skillManager.tickSkillRegister(new revengeChestPlateSkill());
skillManager.tickSkillRegister(new vampireHelmetSkill());

const axeSkill = new infernalAxeSkill();

const axeNames = [
    "§1ぼろぼろの斧",
    "§5斧",
    "§6血の斧",
    "§d血まみれの斧",
    "§b業火の斧"
];

for (const name of axeNames) {
    const s = Object.create(axeSkill);
    s.id = name;
    skillManager.register(s);
}