name: deploy
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean remote behavior pack folder
        uses: appleboy/ssh-action@v1
        with:
          host: 220.158.23.26
          username: vtv
          key: ${{ secrets.VPS_KEY }}
          script: |
            rm -rf /home/vtv/BDS/development_behavior_packs/Gacha-BP
            mkdir -p /home/vtv/BDS/development_behavior_packs/Gacha-BP
      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: 220.158.23.26
          username: vtv
          key: ${{ secrets.VPS_KEY }}
          source: "*"
          target: /home/vtv/BDS/development_behavior_packs/Gacha-BP